kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.ns }}
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: "http-port"
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: "tcp-port"
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP