name: Publish npm

on:
  release:
    types: [created]
  push:
    tags:
      - "*"

jobs:

  build-common:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/common/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install

  publish-client:
    needs: build-common
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/client/
    steps:
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


  publish-server:
    needs: build-common
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/server/
    steps:
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}